from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required, user_passes_test


urlpatterns = [
    path('', views.home, name='home'),
    path('articles', views.ArticlesList.as_view(), name='articles_list'),
    path('articles/create', views.ArticleCreateView.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit', views.ArticleUpdate.as_view(), name='articles_edit'),
    path('langs', views.LangsList.as_view(), name='langs_list'),
    path('langs/create', views.LngCreateView.as_view(), name='create_lang'),
    path('langs/<int:pk>/edit', views.LangsUpdate.as_view(), name='lang_update'),
    path('langs/delete', views.delete_langs, name='lang_del'),
    path("site_infos", views.StaticUpdate.as_view(), name='static_info'),
    path('images/save', views.save_images, name='images_save'),
    path("images/delete", views.delete_image, name='del-img'),
    path('translations', views.TranslationList.as_view(), name='translation_list'),
    path("translations/<int:pk>", views.TranslationGroupDetail.as_view(), name='transl_group_detail'),
    path('translation/edit', views.translation_update, name='translation_edit'),
    path("translations/<int:pk>/edit", views.TranslationGroupUdpate.as_view(), name='transl_group_edit'),
    path("translation_group/create", views.add_trans_group, name='transl_group_create'),
    path("delete", views.delete_item, name='delete'),
    path('delete_alot', views.delete_alot, name='del_alot'),
    path("lang_icon_delete", views.del_lang_icon, name='lang_icon_del'),
    path("add_static_image", views.add_static_image, name='add_static_logos'),
    path("delete_static_image", views.del_statics_image, name='del_static_image'),
    path('delete_article_ctg_images', views.delete_article_group_img, name='art_ctg_image_del'),
    path("about_us/video/delete", views.delete_about_video, name='del_about_video'),
    path('about_us/video/set', views.set_about_video, name='set_about_video'),
    path('login', LoginView.as_view(
        template_name='admin/sing-in.html',
        success_url='/admin/',
    ), name='login_admin'),
    path('logout', views.logout_view, name='logout_url'),
    path('admins', views.AdminsList.as_view(), name='admin_list'),
    path("admins/create", views.AdminCreate.as_view(), name='admins_create'),
    path("admins/<int:pk>/edit", views.AdminUpdate.as_view(), name='admins_edit'),
    path("delete_article_image", views.delete_article_image, name='del_article_img'),
    path("reviews", views.ReviewsList.as_view(), name='review_list'),
    path("reviews/create", views.ReviewsCreate.as_view(), name='review_create'),
    path('reviews/<int:pk>/edit', views.ReviewsUpdate.as_view(), name='review_edit'),
    path('delete_review_image', views.delete_review_image, name='del_review_image'),
    path("partners", views.PartnersList.as_view(), name='partners_list'),
    path("partners/create", views.PartnersCreate.as_view(), name='partners_create'),
    path("partners/<int:pk>/edit", views.PartnersEdit.as_view(), name='partners_edit'),
    path('quick_applications', views.ShortApplicationList.as_view(), name='short_aplic_list'),
    path('quick_applications/<int:pk>/edit', views.ShortApplicationUpdate.as_view(), name='short_aplic_edit'),
    path('categories', views.CategoryList.as_view(), name='category_list'),
    path('categories/create', views.CategoryCreate.as_view(), name='category_create'),
    path("categories/<int:pk>/edit", views.CategoryEdit.as_view(), name='category_edit'),
    path('del_ctg_files', views.del_category_file, name='del_ctg_file'),
    path('atributs', views.AtributsList.as_view(), name='atr_list'),
    path("atributs/create", views.AtributsCreate.as_view(), name='atr_create'),
    path("atributs/<int:pk>", views.AtributsDetailView.as_view(), name='atribut_detail'),
    path("atributs/<int:pk>/edit", views.AtributEdit.as_view(), name='atribut_edit'),
    path("atribut_options/edit", views.AtributOptionEdit.as_view(), name='atr_options_edit'),
    path("atribut_options/get", views.get_option, name='get_atr_option'),
    path('colors', views.ColorsList.as_view(), name='color_list'),
    path("colors/create", views.ColorsCreate.as_view(), name='color_create'),
    path("colors/<int:pk>/edit", views.ColorEdit.as_view(), name='colors_edit'),
    path("products", views.ProductsList.as_view(), name='products_list'),
    path('products/create', views.ProductsCreate.as_view(), name='products_create'),
    path('products/<int:pk>', views.ProductsDetailView.as_view(), name='products_detail'),
    path('products/<int:pk>/edit', views.ProductEdit.as_view(), name='products_edit'),
    path("get_ctg_atributs", views.get_ctg_atributs, name='get_ctg_atributs'),
    path('partner_image_delete', views.delete_partner_image, name='del_partner_img')
    

    #path("fill_db_qwertyuiop", user_passes_test(lambda u: u.is_superuser, login_url='login_admin')(views.fill_db_view))
]
