# Generated by Django 4.1 on 2023-02-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImages',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
