# Generated by Django 4.1 on 2023-02-15 17:24

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(verbose_name='Name')),
                ('deckription', models.JSONField(blank=True, null=True, verbose_name='Deckription')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='partners_images')),
            ],
        ),
    ]
