# Generated by Django 4.1 on 2023-02-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_delete_eventimages_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImages',
        ),
    ]
