# Generated by Django 4.1 on 2023-02-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_shortapplication_nbm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortApplication',
        ),
    ]
