# Generated by Django 4.1 on 2023-02-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_delete_articleimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
