# Generated by Django 4.1 on 2023-02-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
    ]
