# Generated by Django 4.1 on 2023-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_remove_articles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='some', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
