# Generated by Django 4.1 on 2023-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_shortapplication_nbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinformation',
            name='cotalog',
            field=models.FileField(blank=True, null=True, upload_to='cotalog_docx', verbose_name='Cotalog docx'),
        ),
    ]
