# Generated by Django 4.1 on 2023-02-11 14:01

import autoslug.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Atributs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.JSONField(blank=True, null=True, verbose_name='Name'), unique=True)),
                ('deckription', models.JSONField(blank=True, null=True, verbose_name='Deckription')),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_icons')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_image')),
                ('atributs', models.ManyToManyField(blank=True, null=True, to='main.atributs')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('hex', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.JSONField(blank=True, null=True, verbose_name='Name'), unique=True)),
                ('type', models.JSONField(blank=True, null=True, verbose_name='Type')),
                ('manufacturer', models.JSONField(blank=True, null=True, verbose_name='Manuf')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Descr')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='variant_images')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Code')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colors')),
                ('options', models.ManyToManyField(blank=True, null=True, to='main.atributoptions')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.products')),
            ],
        ),
        migrations.AddField(
            model_name='atributoptions',
            name='atribut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.atributs'),
        ),
    ]
