# Generated by Django 4.1 on 2023-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_atributoptions_slug_productvariants_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
    ]
