# Generated by Django 4.1 on 2023-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_colors_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='slug',
            field=models.SlugField(default='some', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
