# Generated by Django 4.1 on 2023-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productvariants_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='slug',
            field=models.SlugField(default='color_red', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
