# Generated by Django 4.1 on 2023-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_colors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cotalog',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Cotalog for download'),
        ),
    ]
