# Generated by Django 4.1 on 2023-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_cotalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cotalog',
            field=models.FileField(blank=True, null=True, upload_to='cotalog_fiels', verbose_name='Cotalog for download'),
        ),
    ]
