# Generated by Django 4.1 on 2023-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_atributoptions_slug_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
