# Generated by Django 4.1 on 2023-02-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_shortapplication_nbm'),
        ('main', '0013_alter_productvariants_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.metatags'),
        ),
    ]
