# Generated by Django 4.1 on 2023-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_products_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
    ]
