# Generated by Django 4.1 on 2023-02-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_productvariants_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('nbm', models.CharField(max_length=255, verbose_name='Nbm')),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='На рассмотрении', max_length=255, verbose_name='Status')),
            ],
        ),
    ]
