# Generated by Django 4.1 on 2023-02-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_shortapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortapplication',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productvariants'),
        ),
    ]
