# Generated by Django 4.1 on 2023-02-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shortapplication_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortapplication',
            name='product',
        ),
    ]
